// Headers generated by Java for functions Java code can call
#ifndef _Included_org_limewire_util_SystemUtils_Crypto
#define _Included_org_limewire_util_SystemUtils_Crypto
#ifdef __cplusplus
extern "C" {
#endif

	// Functions in Crypto.cpp
	JNIEXPORT jboolean JNICALL Java_org_limewire_util_SystemUtils_verifyExecutableSignatureNative(JNIEnv *e, jclass c, jstring path, jbyteArray cert);
#ifdef __cplusplus
}
#endif
#endif
