/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_frostwire_util_filetypes_WinRegistryWrapper */

#ifndef _Included_com_frostwire_util_filetypes_WinRegistryWrapper
#define _Included_com_frostwire_util_filetypes_WinRegistryWrapper
#ifdef __cplusplus
extern "C" {
#endif
#undef com_frostwire_util_filetypes_WinRegistryWrapper_HKEY_CLASSES_ROOT
#define com_frostwire_util_filetypes_WinRegistryWrapper_HKEY_CLASSES_ROOT -2147483648L
#undef com_frostwire_util_filetypes_WinRegistryWrapper_HKEY_CURRENT_USER
#define com_frostwire_util_filetypes_WinRegistryWrapper_HKEY_CURRENT_USER -2147483647L
#undef com_frostwire_util_filetypes_WinRegistryWrapper_HKEY_LOCAL_MACHINE
#define com_frostwire_util_filetypes_WinRegistryWrapper_HKEY_LOCAL_MACHINE -2147483646L
#undef com_frostwire_util_filetypes_WinRegistryWrapper_HKEY_USERS
#define com_frostwire_util_filetypes_WinRegistryWrapper_HKEY_USERS -2147483645L
#undef com_frostwire_util_filetypes_WinRegistryWrapper_HKEY_CURRENT_CONFIG
#define com_frostwire_util_filetypes_WinRegistryWrapper_HKEY_CURRENT_CONFIG -2147483643L
#undef com_frostwire_util_filetypes_WinRegistryWrapper_ERROR_SUCCESS
#define com_frostwire_util_filetypes_WinRegistryWrapper_ERROR_SUCCESS 0L
#undef com_frostwire_util_filetypes_WinRegistryWrapper_ERROR_FILE_NOT_FOUND
#define com_frostwire_util_filetypes_WinRegistryWrapper_ERROR_FILE_NOT_FOUND 2L
#undef com_frostwire_util_filetypes_WinRegistryWrapper_ERROR_ACCESS_DENIED
#define com_frostwire_util_filetypes_WinRegistryWrapper_ERROR_ACCESS_DENIED 5L
#undef com_frostwire_util_filetypes_WinRegistryWrapper_ERROR_ITEM_EXIST
#define com_frostwire_util_filetypes_WinRegistryWrapper_ERROR_ITEM_EXIST 0L
#undef com_frostwire_util_filetypes_WinRegistryWrapper_ERROR_ITEM_NOTEXIST
#define com_frostwire_util_filetypes_WinRegistryWrapper_ERROR_ITEM_NOTEXIST 9L
#undef com_frostwire_util_filetypes_WinRegistryWrapper_MAX_KEY_LENGTH
#define com_frostwire_util_filetypes_WinRegistryWrapper_MAX_KEY_LENGTH 255L
#undef com_frostwire_util_filetypes_WinRegistryWrapper_MAX_VALUE_NAME_LENGTH
#define com_frostwire_util_filetypes_WinRegistryWrapper_MAX_VALUE_NAME_LENGTH 255L
#undef com_frostwire_util_filetypes_WinRegistryWrapper_OPENED_KEY_HANDLE
#define com_frostwire_util_filetypes_WinRegistryWrapper_OPENED_KEY_HANDLE 0L
#undef com_frostwire_util_filetypes_WinRegistryWrapper_ERROR_CODE
#define com_frostwire_util_filetypes_WinRegistryWrapper_ERROR_CODE 1L
#undef com_frostwire_util_filetypes_WinRegistryWrapper_SUBKEYS_NUMBER
#define com_frostwire_util_filetypes_WinRegistryWrapper_SUBKEYS_NUMBER 0L
#undef com_frostwire_util_filetypes_WinRegistryWrapper_VALUES_NUMBER
#define com_frostwire_util_filetypes_WinRegistryWrapper_VALUES_NUMBER 2L
#undef com_frostwire_util_filetypes_WinRegistryWrapper_DELETE
#define com_frostwire_util_filetypes_WinRegistryWrapper_DELETE 65536L
#undef com_frostwire_util_filetypes_WinRegistryWrapper_KEY_QUERY_VALUE
#define com_frostwire_util_filetypes_WinRegistryWrapper_KEY_QUERY_VALUE 1L
#undef com_frostwire_util_filetypes_WinRegistryWrapper_KEY_SET_VALUE
#define com_frostwire_util_filetypes_WinRegistryWrapper_KEY_SET_VALUE 2L
#undef com_frostwire_util_filetypes_WinRegistryWrapper_KEY_CREATE_SUB_KEY
#define com_frostwire_util_filetypes_WinRegistryWrapper_KEY_CREATE_SUB_KEY 4L
#undef com_frostwire_util_filetypes_WinRegistryWrapper_KEY_ENUMERATE_SUB_KEYS
#define com_frostwire_util_filetypes_WinRegistryWrapper_KEY_ENUMERATE_SUB_KEYS 8L
#undef com_frostwire_util_filetypes_WinRegistryWrapper_KEY_READ
#define com_frostwire_util_filetypes_WinRegistryWrapper_KEY_READ 131097L
#undef com_frostwire_util_filetypes_WinRegistryWrapper_KEY_WRITE
#define com_frostwire_util_filetypes_WinRegistryWrapper_KEY_WRITE 131078L
#undef com_frostwire_util_filetypes_WinRegistryWrapper_KEY_ALL_ACCESS
#define com_frostwire_util_filetypes_WinRegistryWrapper_KEY_ALL_ACCESS 983103L
/*
 * Class:     com_frostwire_util_filetypes_WinRegistryWrapper
 * Method:    RegOpenKey
 * Signature: (I[BI)[I
 */
JNIEXPORT jintArray JNICALL Java_com_frostwire_util_filetypes_WinRegistryWrapper_RegOpenKey
  (JNIEnv *, jclass, jint, jbyteArray, jint);

/*
 * Class:     com_frostwire_util_filetypes_WinRegistryWrapper
 * Method:    RegCloseKey
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_frostwire_util_filetypes_WinRegistryWrapper_RegCloseKey
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_frostwire_util_filetypes_WinRegistryWrapper
 * Method:    RegCreateKeyEx
 * Signature: (I[B)[I
 */
JNIEXPORT jintArray JNICALL Java_com_frostwire_util_filetypes_WinRegistryWrapper_RegCreateKeyEx
  (JNIEnv *, jclass, jint, jbyteArray);

/*
 * Class:     com_frostwire_util_filetypes_WinRegistryWrapper
 * Method:    RegDeleteKey
 * Signature: (I[B)I
 */
JNIEXPORT jint JNICALL Java_com_frostwire_util_filetypes_WinRegistryWrapper_RegDeleteKey
  (JNIEnv *, jclass, jint, jbyteArray);

/*
 * Class:     com_frostwire_util_filetypes_WinRegistryWrapper
 * Method:    RegFlushKey
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_frostwire_util_filetypes_WinRegistryWrapper_RegFlushKey
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_frostwire_util_filetypes_WinRegistryWrapper
 * Method:    RegQueryValueEx
 * Signature: (I[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_frostwire_util_filetypes_WinRegistryWrapper_RegQueryValueEx
  (JNIEnv *, jclass, jint, jbyteArray);

/*
 * Class:     com_frostwire_util_filetypes_WinRegistryWrapper
 * Method:    RegSetValueEx
 * Signature: (I[B[B)I
 */
JNIEXPORT jint JNICALL Java_com_frostwire_util_filetypes_WinRegistryWrapper_RegSetValueEx
  (JNIEnv *, jclass, jint, jbyteArray, jbyteArray);

/*
 * Class:     com_frostwire_util_filetypes_WinRegistryWrapper
 * Method:    RegDeleteValue
 * Signature: (I[B)I
 */
JNIEXPORT jint JNICALL Java_com_frostwire_util_filetypes_WinRegistryWrapper_RegDeleteValue
  (JNIEnv *, jclass, jint, jbyteArray);

/*
 * Class:     com_frostwire_util_filetypes_WinRegistryWrapper
 * Method:    RegQueryInfoKey
 * Signature: (I)[I
 */
JNIEXPORT jintArray JNICALL Java_com_frostwire_util_filetypes_WinRegistryWrapper_RegQueryInfoKey
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_frostwire_util_filetypes_WinRegistryWrapper
 * Method:    RegEnumKeyEx
 * Signature: (III)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_frostwire_util_filetypes_WinRegistryWrapper_RegEnumKeyEx
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     com_frostwire_util_filetypes_WinRegistryWrapper
 * Method:    RegEnumValue
 * Signature: (III)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_frostwire_util_filetypes_WinRegistryWrapper_RegEnumValue
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     com_frostwire_util_filetypes_WinRegistryWrapper
 * Method:    FindMimeFromData
 * Signature: ([B[B)[B
 */
//JNIEXPORT jbyteArray JNICALL Java_com_frostwire_util_filetypes_WinRegistryWrapper_FindMimeFromData
//  (JNIEnv *, jclass, jbyteArray, jbyteArray);

/*
 * Class:     com_frostwire_util_filetypes_WinRegistryWrapper
 * Method:    ExpandEnvironmentStrings
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_frostwire_util_filetypes_WinRegistryWrapper_ExpandEnvironmentStrings
  (JNIEnv *, jclass, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
